### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kenuoseclab** [qi4L/Blackout-go#1]
Loading Blackout.sys driver ...
Service already exists.
driver loaded successfully !!
Failed to open handle to driver !!
2024/09/29 21:24:49 CreateFile APi 出错，原因 -> The system cannot find the file specified.

**Comment by qi4L** [comment]
没找到sys文件，你可以手工的调试一下，看路径是否正确

**Comment by kenuoseclab** [comment]
> 没找到sys文件，你可以手工的调试一下，看路径是否正确

路径正确的，我是win11
